// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgIPPTb5ATk-XKitMGwV9OoX7fiZ85gwI',
    appId: '1:155486872657:web:16b809981e1d8b1da9c470',
    messagingSenderId: '155486872657',
    projectId: 'gwen-chat',
    authDomain: 'gwen-chat.firebaseapp.com',
    storageBucket: 'gwen-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDak4YW5HJ4R6eZI54jcfohpL6ypQ_eehE',
    appId: '1:155486872657:android:f68833bb43cbc853a9c470',
    messagingSenderId: '155486872657',
    projectId: 'gwen-chat',
    storageBucket: 'gwen-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUq1FZFw1gPYPa2rvLnk4l4PiSGhjTsWA',
    appId: '1:155486872657:ios:7a3b9298fc885d2ea9c470',
    messagingSenderId: '155486872657',
    projectId: 'gwen-chat',
    storageBucket: 'gwen-chat.appspot.com',
    iosBundleId: 'com.example.gwenChat',
  );
}
